//! Single PTY-backed terminal session with runtime-free I/O.
//!
//! [`Session`] owns one PTY-backed terminal session. The caller drives it
//! from its own poll loop: read [`Session::fd`] and [`Session::interests`],
//! call [`Session::pump_io`] whenever the fd is ready or after any call that
//! changes the session, and repeat while [`Session::needs_pump`] reports
//! that more work is available without waiting for a new readiness edge.
//!
//! The session never owns a poll loop and takes no readiness flags: the fd is
//! non-blocking, so `pump_io` learns what is possible from the `WouldBlock`
//! results of its own `read`/`write` calls. Owning, identifying, and
//! scheduling several sessions is the caller's responsibility. One `pump_io`
//! call is the scheduling quantum; a multi-session loop should rotate among
//! runnable sessions rather than draining one session to idle.
//!
//! Application input and terminal replies share one FIFO write queue. A reply
//! is appended in chronological order and decoding pauses until that reply is
//! fully written, so at most one reply (bounded by a fixed internal size) is
//! ever pending and replies never overtake previously accepted input. The
//! write queue itself is unbounded; callers apply backpressure via metrics.
//!
//! Child exit and PTY EOF are tracked separately: reaping the child does not
//! disable I/O, so any remaining master-side output can still be drained until
//! EOF.

use std::{
    io::{self, ErrorKind, Read, Write},
    ops::Range,
    os::fd::{AsRawFd, RawFd},
    process::{Command, ExitStatus},
};

use crate::{
    pty::{ClosingPtyProcess, PtyProcess, SignalOutcome},
    size::Size,
    terminal::{TerminalAction, TerminalState},
};

/// Maximum size of a single pending terminal reply.
///
/// The emulator answers a CPR (cursor position report) request with
/// `ESC [ <row> ; <col> R`. Both numbers are at most five digits because the
/// grid is `u16` sized, so the longest reply is `ESC [ 65536 ; 65536 R`,
/// which is 14 bytes. A single decode unit must produce at most this many
/// reply bytes; the invariant is pinned by tests.
const MAX_PENDING_REPLY_BYTES: usize = 14;

/// Maximum raw bytes held between reading from the PTY and decoding.
const READ_BUFFER_LIMIT: usize = 65536;

/// Maximum bytes a single `pump_io` processes (read + decode + write).
const PUMP_BYTE_QUANTUM: usize = 65536;

/// Maximum syscalls a single `pump_io` attempts.
const PUMP_SYSCALL_QUANTUM: usize = 64;

/// Drop already-written `outbound` prefix once it reaches this size.
const OUTBOUND_COMPACT_THRESHOLD: usize = 4096;

/// Drop already-decoded `read_buffer` prefix once it reaches this size.
const READ_COMPACT_THRESHOLD: usize = 4096;

/// Read/write interests an event loop should register for the session's fd.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct Interests {
    /// Whether readable events should be polled.
    pub readable: bool,
    /// Whether writable events should be polled.
    pub writable: bool,
}

/// One snapshot of a session's activity counters.
///
/// `metrics()` returns a value snapshot, so callers can hold values taken
/// before and after a `pump_io` and diff them. Cumulative counters are never
/// reset for the lifetime of the session; current values are derived from the
/// live buffers at snapshot time. Maximum fields record peaks observed when
/// the corresponding buffers grow, not only at pump boundaries.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct SessionMetrics {
    /// Cumulative `pump_io` calls.
    pub pump_calls: u64,
    /// Cumulative pumps that ended with the internal budget exhausted.
    pub pump_budget_exhaustions: u64,
    /// Cumulative bytes read from the PTY.
    pub pty_bytes_read: u64,
    /// Cumulative bytes written to the PTY.
    pub pty_bytes_written: u64,
    /// Cumulative bytes fed to the terminal emulator.
    pub terminal_bytes_processed: u64,
    /// Cumulative reply bytes generated by the terminal emulator.
    pub terminal_reply_bytes_generated: u64,
    /// Cumulative bytes accepted through `enqueue_input`.
    pub input_bytes_enqueued: u64,
    /// Cumulative `read` syscalls attempted.
    pub read_syscalls: u64,
    /// Cumulative `write` syscalls attempted.
    pub write_syscalls: u64,
    /// Cumulative `read` syscalls that returned `WouldBlock`.
    pub read_would_block: u64,
    /// Cumulative `write` syscalls that returned `WouldBlock`.
    pub write_would_block: u64,

    /// Current raw bytes read from the PTY but not yet decoded.
    pub buffered_read_bytes: usize,
    /// Current bytes not yet written to the PTY (input plus reply).
    pub pending_write_bytes: usize,
    /// Current unsent application input bytes.
    pub pending_input_bytes: usize,
    /// Current unsent terminal reply bytes.
    pub pending_reply_bytes: usize,
    /// Current retained scrollback lines.
    pub scrollback_lines: usize,
    /// Current retained scrollback cells.
    pub scrollback_cells: usize,

    /// Highest observed `buffered_read_bytes`.
    pub max_buffered_read_bytes: usize,
    /// Highest observed `pending_write_bytes`.
    pub max_pending_write_bytes: usize,
    /// Highest observed `scrollback_lines`.
    pub max_scrollback_lines: usize,
    /// Highest observed `scrollback_cells`.
    pub max_scrollback_cells: usize,
}

/// Observable lifecycle phase of a session.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SessionStatus {
    /// PTY master open, I/O active.
    Live,
    /// PTY EOF observed; remaining output drained.
    Eof,
    /// Logically closed; master closed, awaiting reap.
    Closing,
    /// Direct child reaped and I/O finished; the session is spent.
    Reaped,
}

/// Direction cursor used for read/write fairness within one pump.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Direction {
    Read,
    Write,
}

impl Direction {
    fn opposite(self) -> Self {
        match self {
            Self::Read => Self::Write,
            Self::Write => Self::Read,
        }
    }
}

/// Lifecycle phase of one session.
///
/// Tracks I/O and logical close. Child exit is stored separately in
/// [`Session::exit_status`]; reaping alone does not enter [`Phase::Reaped`].
#[derive(Clone, Copy, PartialEq, Eq)]
enum Phase {
    Live,
    Eof,
    Closing,
    Reaped,
}

/// Owned PTY side of a session.
enum Pty {
    Live(PtyProcess),
    Closing(ClosingPtyProcess),
}

impl Pty {
    fn is_live(&self) -> bool {
        matches!(self, Self::Live(_))
    }

    fn fd(&self) -> Option<RawFd> {
        match self {
            Self::Live(pty) => Some(pty.as_raw_fd()),
            Self::Closing(_) => None,
        }
    }
}

/// Cumulative counters that never reset.
#[derive(Default)]
struct Cumulative {
    pump_calls: u64,
    pump_budget_exhaustions: u64,
    pty_bytes_read: u64,
    pty_bytes_written: u64,
    terminal_bytes_processed: u64,
    terminal_reply_bytes_generated: u64,
    input_bytes_enqueued: u64,
    read_syscalls: u64,
    write_syscalls: u64,
    read_would_block: u64,
    write_would_block: u64,
    max_buffered_read_bytes: usize,
    max_pending_write_bytes: usize,
    max_scrollback_lines: usize,
    max_scrollback_cells: usize,
}

/// A single PTY-backed terminal session.
///
/// The session owns the PTY master fd, the emulator state, a bounded read
/// buffer, an unbounded write queue, and the child-process lifecycle, but
/// never owns a poll loop. Register [`Session::fd`] with
/// [`Session::interests`], call [`Session::pump_io`] when the fd is ready (or
/// after any state change), and repeat while [`Session::needs_pump`] returns
/// `true` before waiting in the poll loop. With several sessions, treat each
/// `pump_io` as one quantum and rotate among runnable sessions.
///
/// # Drop behavior
///
/// Dropping the session performs best-effort cleanup: the remaining child is
/// force-killed and reaped, which may block. Failures cannot be reported from
/// `Drop`; call [`Session::shutdown`] to observe the result.
pub struct Session {
    pty: Option<Pty>,
    term: TerminalState,
    phase: Phase,
    /// Cached status once the direct child has been reaped.
    ///
    /// Independent of [`Self::phase`]: I/O may continue until PTY EOF after
    /// the child exits.
    exit_status: Option<ExitStatus>,
    /// Raw bytes read from the PTY but not yet decoded.
    read_buffer: Vec<u8>,
    /// Number of leading `read_buffer` bytes already decoded.
    read_offset: usize,
    /// Bytes waiting to be written, in chronological order.
    outbound: Vec<u8>,
    /// Number of leading `outbound` bytes already written.
    write_offset: usize,
    /// Range of the one unsent terminal reply inside `outbound`.
    ///
    /// While set, reading and decoding are paused until the reply is fully
    /// written, so at most one reply is ever pending.
    pending_reply_range: Option<Range<usize>>,
    /// Direction the next pump should start with.
    direction: Direction,
    /// Whether the most recent pump stopped reading on `WouldBlock`.
    read_would_block: bool,
    /// Whether the most recent pump stopped writing on `WouldBlock`.
    write_would_block: bool,
    cumulative: Cumulative,
}

impl Session {
    /// Spawns `command` in a new PTY-backed terminal session.
    ///
    /// On failure no session is created and any opened PTY fd and child are
    /// reclaimed.
    pub fn new(command: &mut Command, size: Size) -> io::Result<Self> {
        let mut pty = PtyProcess::spawn(command, size)?;
        if let Err(err) = pty.set_nonblocking(true) {
            // Reclaim the fd and the child before reporting the failure.
            let mut closing = pty.into_closing();
            let _ = closing.signal_kill();
            let _ = closing.wait_and_reap();
            return Err(err);
        }
        let term = TerminalState::new(size);
        Ok(Self {
            pty: Some(Pty::Live(pty)),
            term,
            phase: Phase::Live,
            exit_status: None,
            read_buffer: Vec::new(),
            read_offset: 0,
            outbound: Vec::new(),
            write_offset: 0,
            pending_reply_range: None,
            direction: Direction::Write,
            read_would_block: false,
            write_would_block: false,
            cumulative: Cumulative::default(),
        })
    }

    /// Returns the fd to register with an event loop, if any.
    ///
    /// When `Some`, the fd is always non-blocking; `Session` sets that mode at
    /// construction and never changes it. `None` is returned after a logical
    /// close or once the session is spent; callers should unregister the
    /// previous registration then. Reaping the child while the master is still
    /// open does not clear the fd.
    pub fn fd(&self) -> Option<RawFd> {
        if self.phase == Phase::Closing || self.phase == Phase::Reaped {
            return None;
        }
        self.pty.as_ref().and_then(Pty::fd)
    }

    /// Returns the poll interests the fd should currently be registered with.
    ///
    /// Re-read after any state change (notably after `enqueue_input`, which
    /// may turn on the writable interest) and after every `pump_io`.
    pub fn interests(&self) -> Interests {
        if self.phase == Phase::Closing || self.phase == Phase::Reaped {
            return Interests::default();
        }
        let mut interests = Interests::default();
        if self.phase != Phase::Eof
            && !self.read_paused()
            && self.pty.as_ref().is_some_and(Pty::is_live)
        {
            interests.readable = true;
        }
        if !self.outbound_empty() {
            interests.writable = true;
        }
        interests
    }

    /// Whether `pump_io` has more work that does not need a new readiness
    /// edge.
    ///
    /// Returns `false` when the last pump stopped because a `read` or `write`
    /// returned `WouldBlock`; the caller should then wait for the interest
    /// reported by [`Session::interests`]. Returns `true` when internal work
    /// (buffered decoding, a pending reply, or a pump interrupted by the
    /// internal budget) is still executable immediately, which an
    /// edge-triggered loop must drain before blocking. With several sessions,
    /// prefer rotating among `needs_pump` sessions instead of draining one
    /// session in a tight loop.
    pub fn needs_pump(&self) -> bool {
        if self.phase == Phase::Closing || self.phase == Phase::Reaped {
            return false;
        }
        if !self.outbound_empty() && !self.write_would_block {
            return true;
        }
        if self.phase == Phase::Live && !self.read_paused() && !self.read_would_block {
            return true;
        }
        self.buffered_read_len() > 0 && !self.read_paused()
    }

    /// Advances the session: writes queued bytes, reads and decodes PTY
    /// output, and detects EOF, bounded by an internal budget.
    ///
    /// The fd is non-blocking, so no readiness flags are taken; `WouldBlock`
    /// results decide how far a single call goes. After a logical close this
    /// is a successful no-op.
    pub fn pump_io(&mut self) -> io::Result<()> {
        if self.phase == Phase::Closing || self.phase == Phase::Reaped {
            return Ok(());
        }
        self.cumulative.pump_calls = self.cumulative.pump_calls.saturating_add(1);
        self.read_would_block = false;
        self.write_would_block = false;
        let mut budget = Budget::new(PUMP_BYTE_QUANTUM, PUMP_SYSCALL_QUANTUM);
        let mut direction = self.direction;
        for _ in 0..2 {
            if budget.exhausted() {
                break;
            }
            // Start with the direction that actually has work, so a session
            // with nothing to write is not blocked behind the write phase.
            if !self.has_direction_work(direction) {
                direction = direction.opposite();
                if !self.has_direction_work(direction) {
                    break;
                }
            }
            let progressed = match direction {
                Direction::Write => self.write_phase(&mut budget)?,
                Direction::Read => self.read_phase(&mut budget)?,
            };
            if !progressed {
                break;
            }
            direction = direction.opposite();
            if !self.has_direction_work(direction) {
                break;
            }
        }
        self.direction = direction;
        if budget.exhausted() {
            self.cumulative.pump_budget_exhaustions =
                self.cumulative.pump_budget_exhaustions.saturating_add(1);
        }
        Ok(())
    }

    /// Enqueues application input (typically the output of
    /// [`encode_key`](crate::encode_key) or
    /// [`encode_paste`](crate::encode_paste)) to be written to the PTY.
    ///
    /// All bytes are accepted while the session is open and appended to the
    /// write queue in chronological order. The session applies no backpressure
    /// policy; compare the encoded length against
    /// `metrics().pending_write_bytes` to decide whether to enqueue, hold the
    /// input on the caller side, or drop it. A closed session returns
    /// [`ErrorKind::BrokenPipe`].
    pub fn enqueue_input(&mut self, bytes: &[u8]) -> io::Result<()> {
        if self.phase != Phase::Live && self.phase != Phase::Eof {
            return Err(io::Error::new(ErrorKind::BrokenPipe, "session is closed"));
        }
        self.outbound.extend_from_slice(bytes);
        self.cumulative.input_bytes_enqueued = self
            .cumulative
            .input_bytes_enqueued
            .saturating_add(bytes.len() as u64);
        self.write_would_block = false;
        self.update_maxes();
        Ok(())
    }

    /// Resizes the session, updating both the kernel PTY size and the
    /// emulator.
    ///
    /// Reapplying the current size succeeds without a syscall. The ioctl runs
    /// first; the emulator size is only updated when the ioctl succeeds. A
    /// closed session returns [`ErrorKind::BrokenPipe`].
    pub fn resize(&mut self, size: Size) -> io::Result<()> {
        if self.phase != Phase::Live && self.phase != Phase::Eof {
            return Err(io::Error::new(ErrorKind::BrokenPipe, "session is closed"));
        }
        if self.term.size() == size {
            return Ok(());
        }
        let Some(Pty::Live(pty)) = self.pty.as_mut() else {
            return Err(io::Error::new(ErrorKind::BrokenPipe, "session is closed"));
        };
        pty.resize(size)?;
        self.term.resize(size);
        Ok(())
    }

    /// Logically closes the session.
    ///
    /// This synchronously discards the write queue, pending reply and unread
    /// bytes, and closes the PTY master. The child is kept in a private
    /// closing state until reaped. After closing, `pump_io` is a successful
    /// no-op, `enqueue_input` and `resize` return [`ErrorKind::BrokenPipe`],
    /// while the final terminal state, metrics, process polling and signal
    /// delivery remain available until the child is reaped. Idempotent.
    pub fn close(&mut self) {
        if self.phase == Phase::Reaped {
            return;
        }
        if self.phase != Phase::Closing {
            self.outbound.clear();
            self.write_offset = 0;
            self.pending_reply_range = None;
            self.read_buffer.clear();
            self.read_offset = 0;
            self.phase = Phase::Closing;
            let pty = self.pty.take();
            self.pty = Some(match pty {
                Some(Pty::Live(pty)) => Pty::Closing(pty.into_closing()),
                other => other.expect("pty is present while closing"),
            });
        }
    }

    /// Observes and reaps the child without blocking.
    ///
    /// Returns `Ok(Some(status))` once the child has exited, caching the
    /// status; later calls return the same value. Reaping does not stop PTY
    /// I/O: while the master is still open the session stays readable until
    /// EOF. The session enters [`SessionStatus::Reaped`] only after the child
    /// is reaped and I/O is finished (EOF or a logical close).
    pub fn try_wait(&mut self) -> io::Result<Option<ExitStatus>> {
        if let Some(status) = self.exit_status {
            return Ok(Some(status));
        }
        match self.pty.as_mut() {
            Some(Pty::Live(pty)) => {
                let status = pty.try_wait()?;
                if let Some(status) = status {
                    self.note_exit(status);
                    Ok(Some(status))
                } else {
                    Ok(None)
                }
            }
            Some(Pty::Closing(pty)) => {
                if pty.poll_exit()?.is_none() {
                    return Ok(None);
                }
                let status = pty.wait_and_reap()?;
                self.exit_status = Some(status);
                self.phase = Phase::Reaped;
                Ok(Some(status))
            }
            None => Ok(None),
        }
    }

    /// Blocks until the child exits and returns its status.
    ///
    /// After a successful reap the status is cached and later calls return it.
    /// As with [`Session::try_wait`], reaping alone does not disable PTY I/O.
    pub fn wait(&mut self) -> io::Result<ExitStatus> {
        if let Some(status) = self.exit_status {
            return Ok(status);
        }
        match self.pty.as_mut() {
            Some(Pty::Live(pty)) => {
                let status = pty.wait()?;
                self.note_exit(status);
                Ok(status)
            }
            Some(Pty::Closing(pty)) => {
                let status = pty.wait_and_reap()?;
                self.exit_status = Some(status);
                self.phase = Phase::Reaped;
                Ok(status)
            }
            None => Err(io::Error::new(
                ErrorKind::BrokenPipe,
                "session already reaped",
            )),
        }
    }

    /// Returns read-only access to the session's terminal state.
    ///
    /// Available in every phase, including after the child has been reaped.
    /// Call [`TerminalState::snapshot`] on the returned reference for an owned
    /// copy.
    pub fn terminal_state(&self) -> &TerminalState {
        &self.term
    }

    /// Returns a snapshot of the session's activity counters.
    pub fn metrics(&self) -> SessionMetrics {
        let buffered_read_bytes = self.buffered_read_len();
        let pending_write_bytes = self.unsent();
        let pending_reply_bytes = self.pending_reply_unsent();
        let pending_input_bytes = pending_write_bytes.saturating_sub(pending_reply_bytes);
        let scrollback_lines = self.term.scrollback_len();
        let scrollback_cells = self.term.scrollback_cells();
        SessionMetrics {
            pump_calls: self.cumulative.pump_calls,
            pump_budget_exhaustions: self.cumulative.pump_budget_exhaustions,
            pty_bytes_read: self.cumulative.pty_bytes_read,
            pty_bytes_written: self.cumulative.pty_bytes_written,
            terminal_bytes_processed: self.cumulative.terminal_bytes_processed,
            terminal_reply_bytes_generated: self.cumulative.terminal_reply_bytes_generated,
            input_bytes_enqueued: self.cumulative.input_bytes_enqueued,
            read_syscalls: self.cumulative.read_syscalls,
            write_syscalls: self.cumulative.write_syscalls,
            read_would_block: self.cumulative.read_would_block,
            write_would_block: self.cumulative.write_would_block,
            buffered_read_bytes,
            pending_write_bytes,
            pending_input_bytes,
            pending_reply_bytes,
            scrollback_lines,
            scrollback_cells,
            max_buffered_read_bytes: self.cumulative.max_buffered_read_bytes,
            max_pending_write_bytes: self.cumulative.max_pending_write_bytes,
            max_scrollback_lines: self.cumulative.max_scrollback_lines,
            max_scrollback_cells: self.cumulative.max_scrollback_cells,
        }
    }

    /// Removes the oldest scrollback lines until both limits hold.
    ///
    /// Delegates to [`TerminalState::trim_scrollback`]; lines are removed
    /// whole, oldest first, and either limit at zero clears the history.
    pub fn trim_scrollback(&mut self, max_lines: usize, max_cells: usize) {
        self.term.trim_scrollback(max_lines, max_cells);
    }

    /// Returns the observable lifecycle phase of the session.
    pub fn status(&self) -> SessionStatus {
        match self.phase {
            Phase::Live => SessionStatus::Live,
            Phase::Eof => SessionStatus::Eof,
            Phase::Closing => SessionStatus::Closing,
            Phase::Reaped => SessionStatus::Reaped,
        }
    }

    /// Sends a graceful termination signal (SIGTERM) to the session's process
    /// group.
    pub fn terminate(&mut self) -> io::Result<SignalOutcome> {
        match self.pty.as_mut() {
            Some(Pty::Live(pty)) => pty.signal_group(libc::SIGTERM),
            Some(Pty::Closing(pty)) => pty.signal_terminate(),
            None => Err(io::Error::new(
                ErrorKind::BrokenPipe,
                "session already reaped",
            )),
        }
    }

    /// Sends a force-termination signal (SIGKILL) to the session's process
    /// group.
    pub fn force_terminate(&mut self) -> io::Result<SignalOutcome> {
        match self.pty.as_mut() {
            Some(Pty::Live(pty)) => pty.signal_group(libc::SIGKILL),
            Some(Pty::Closing(pty)) => pty.signal_kill(),
            None => Err(io::Error::new(
                ErrorKind::BrokenPipe,
                "session already reaped",
            )),
        }
    }

    /// Cleans up this session, force-killing and reaping the direct child.
    ///
    /// This consumes the session and may block while reaping.
    pub fn shutdown(mut self) -> io::Result<ExitStatus> {
        if let Some(status) = self.exit_status.take() {
            // Child already reaped; still close the master if it remains.
            match self.pty.take() {
                Some(Pty::Live(pty)) => {
                    let _ = pty.into_closing();
                }
                Some(Pty::Closing(_)) | None => {}
            }
            return Ok(status);
        }
        let mut closing = match self.pty.take() {
            Some(Pty::Live(pty)) => pty.into_closing(),
            Some(Pty::Closing(closing)) => closing,
            None => {
                return Err(io::Error::new(
                    ErrorKind::BrokenPipe,
                    "session already reaped",
                ));
            }
        };
        let _ = closing.signal_kill();
        closing.wait_and_reap()
    }

    /// Records a freshly reaped exit status and enters `Reaped` if I/O is done.
    fn note_exit(&mut self, status: ExitStatus) {
        self.exit_status = Some(status);
        if self.phase == Phase::Eof {
            self.phase = Phase::Reaped;
        }
    }

    /// Marks PTY EOF and enters `Reaped` when the child was already reaped.
    fn note_eof(&mut self) {
        self.phase = Phase::Eof;
        if self.exit_status.is_some() {
            self.phase = Phase::Reaped;
        }
    }

    /// Whether decoding and reading are paused on a pending terminal reply.
    fn read_paused(&self) -> bool {
        self.pending_reply_range.is_some()
    }

    /// Returns whether `outbound` holds any unsent bytes.
    fn outbound_empty(&self) -> bool {
        self.outbound.len() == self.write_offset
    }

    /// Returns the number of unsent bytes currently held.
    fn unsent(&self) -> usize {
        self.outbound.len() - self.write_offset
    }

    /// Returns the number of buffered but not yet decoded read bytes.
    fn buffered_read_len(&self) -> usize {
        self.read_buffer.len() - self.read_offset
    }

    /// Returns the number of unsent reply bytes currently held.
    ///
    /// Counts only the intersection of the unsent outbound range and the
    /// pending reply range, so leading unsent input is not counted as reply.
    fn pending_reply_unsent(&self) -> usize {
        pending_reply_unsent_len(self.write_offset, self.pending_reply_range.as_ref())
    }

    /// Updates the running maxima tracked in the cumulative counters.
    fn update_maxes(&mut self) {
        self.cumulative.max_buffered_read_bytes = self
            .cumulative
            .max_buffered_read_bytes
            .max(self.buffered_read_len());
        self.cumulative.max_pending_write_bytes =
            self.cumulative.max_pending_write_bytes.max(self.unsent());
        self.cumulative.max_scrollback_lines = self
            .cumulative
            .max_scrollback_lines
            .max(self.term.scrollback_len());
        self.cumulative.max_scrollback_cells = self
            .cumulative
            .max_scrollback_cells
            .max(self.term.scrollback_cells());
    }

    /// Drops the already-written prefix of `outbound` when it grows large.
    fn compact_outbound_if_needed(&mut self) {
        if self.write_offset == 0 {
            return;
        }
        if self.write_offset < OUTBOUND_COMPACT_THRESHOLD && !self.outbound_empty() {
            return;
        }
        if let Some(range) = self.pending_reply_range.as_ref()
            && self.write_offset >= range.end
        {
            self.pending_reply_range = None;
        }
        let drained = self.write_offset;
        self.outbound.drain(..drained);
        if let Some(range) = self.pending_reply_range.as_mut() {
            // write_offset may sit inside the reply range after a partial write.
            range.start = range.start.saturating_sub(drained);
            range.end -= drained;
        }
        self.write_offset = 0;
    }

    /// Drops the already-decoded prefix of `read_buffer` when it grows large.
    fn compact_read_buffer_if_needed(&mut self) {
        if self.read_offset == 0 {
            return;
        }
        if self.read_offset < READ_COMPACT_THRESHOLD && self.buffered_read_len() > 0 {
            return;
        }
        self.read_buffer.drain(..self.read_offset);
        self.read_offset = 0;
    }

    /// Whether the given direction currently has work.
    fn has_direction_work(&self, direction: Direction) -> bool {
        match direction {
            Direction::Write => !self.outbound_empty(),
            Direction::Read => {
                (self.buffered_read_len() > 0 && !self.read_paused())
                    || (self.phase == Phase::Live
                        && !self.read_paused()
                        && self.pty.as_ref().is_some_and(Pty::is_live))
            }
        }
    }

    /// Writes pending bytes, bounded by the pump budget.
    fn write_phase(&mut self, budget: &mut Budget) -> io::Result<bool> {
        let mut progressed = false;
        loop {
            if budget.exhausted() {
                break;
            }
            if self.phase == Phase::Closing || self.phase == Phase::Reaped {
                break;
            }
            let unsent = self.unsent();
            if unsent == 0 {
                break;
            }
            let cap = budget.bytes_left().min(unsent);
            if cap == 0 {
                break;
            }
            let Some(Pty::Live(mut pty)) = self.pty.take() else {
                break;
            };
            let start = self.write_offset;
            let result = pty.write(&self.outbound[start..start + cap]);
            self.pty = Some(Pty::Live(pty));
            budget.consume(0, 1);
            self.cumulative.write_syscalls = self.cumulative.write_syscalls.saturating_add(1);
            match result {
                Ok(0) => break,
                Ok(n) => {
                    self.write_offset += n;
                    budget.consume(n, 0);
                    self.cumulative.pty_bytes_written =
                        self.cumulative.pty_bytes_written.saturating_add(n as u64);
                    self.compact_outbound_if_needed();
                    progressed = true;
                }
                Err(err) if err.kind() == ErrorKind::WouldBlock => {
                    self.cumulative.write_would_block =
                        self.cumulative.write_would_block.saturating_add(1);
                    self.write_would_block = true;
                    break;
                }
                Err(err) if err.kind() == ErrorKind::Interrupted => break,
                Err(err) => return Err(err),
            }
        }
        // If the pending reply was fully written but later input remains,
        // decoding may resume.
        if let Some(range) = self.pending_reply_range.as_ref()
            && self.write_offset >= range.end
        {
            self.pending_reply_range = None;
        }
        Ok(progressed)
    }

    /// Reads and decodes bytes, bounded by the pump budget.
    fn read_phase(&mut self, budget: &mut Budget) -> io::Result<bool> {
        let mut progressed = false;
        progressed |= self.decode_buffered(budget)? > 0;

        if self.phase != Phase::Live || self.read_paused() {
            return Ok(progressed);
        }

        loop {
            if budget.exhausted() {
                break;
            }
            if self.read_paused() || self.phase != Phase::Live {
                break;
            }
            let room = READ_BUFFER_LIMIT.saturating_sub(self.buffered_read_len());
            if room == 0 {
                break;
            }
            let cap = budget.bytes_left().min(room);
            if cap == 0 {
                break;
            }
            self.compact_read_buffer_if_needed();
            let Some(Pty::Live(mut pty)) = self.pty.take() else {
                break;
            };
            let start = self.read_buffer.len();
            self.read_buffer.resize(start + cap, 0);
            let result = pty.read(&mut self.read_buffer[start..]);
            self.pty = Some(Pty::Live(pty));
            budget.consume(0, 1);
            self.cumulative.read_syscalls = self.cumulative.read_syscalls.saturating_add(1);
            match result {
                Ok(0) => {
                    self.read_buffer.truncate(start);
                    self.note_eof();
                    break;
                }
                Ok(n) => {
                    self.read_buffer.truncate(start + n);
                    budget.consume(n, 0);
                    self.cumulative.pty_bytes_read =
                        self.cumulative.pty_bytes_read.saturating_add(n as u64);
                    self.update_maxes();
                    progressed = true;
                    self.decode_buffered(budget)?;
                    if self.read_paused() {
                        break;
                    }
                }
                Err(err) if err.kind() == ErrorKind::WouldBlock => {
                    self.read_buffer.truncate(start);
                    self.cumulative.read_would_block =
                        self.cumulative.read_would_block.saturating_add(1);
                    self.read_would_block = true;
                    break;
                }
                Err(err) if err.kind() == ErrorKind::Interrupted => {
                    self.read_buffer.truncate(start);
                    break;
                }
                Err(err) if err.raw_os_error() == Some(libc::EIO) => {
                    // PTY slave close is reported as EIO on some platforms;
                    // normalize it to EOF.
                    self.read_buffer.truncate(start);
                    self.note_eof();
                    break;
                }
                Err(err) => {
                    self.read_buffer.truncate(start);
                    return Err(err);
                }
            }
        }
        Ok(progressed)
    }

    /// Decodes already-buffered raw bytes, one at a time, until paused, empty,
    /// or the budget is exhausted. Returns the number of bytes decoded.
    fn decode_buffered(&mut self, budget: &mut Budget) -> io::Result<usize> {
        let mut decoded = 0;
        loop {
            if budget.bytes_left() == 0 {
                break;
            }
            if self.read_paused() || self.buffered_read_len() == 0 {
                break;
            }
            let byte = self.read_buffer[self.read_offset];
            self.read_offset += 1;
            budget.consume(1, 0);
            self.cumulative.terminal_bytes_processed =
                self.cumulative.terminal_bytes_processed.saturating_add(1);
            self.decode_byte(byte)?;
            decoded += 1;
        }
        self.compact_read_buffer_if_needed();
        Ok(decoded)
    }

    /// Feeds one byte into the emulator and appends any produced reply.
    ///
    /// A reply is appended to the write queue unconditionally, preserving
    /// chronological order behind previously accepted input, and decoding
    /// pauses until that reply is fully written. At most one reply is pending
    /// at a time because no further bytes are decoded while paused.
    fn decode_byte(&mut self, byte: u8) -> io::Result<()> {
        self.term.feed(&[byte]);
        let actions = self.term.drain_actions();
        let mut reply = Vec::new();
        for action in actions {
            let TerminalAction::WritePty(bytes) = action;
            reply.extend_from_slice(&bytes);
        }
        // Scrollback may have grown even when no reply was produced.
        self.update_maxes();
        if reply.is_empty() {
            return Ok(());
        }
        if reply.len() > MAX_PENDING_REPLY_BYTES {
            return Err(io::Error::new(
                ErrorKind::InvalidData,
                "terminal reply exceeds the internal pending reply bound",
            ));
        }
        let start = self.outbound.len();
        self.outbound.extend_from_slice(&reply);
        self.cumulative.terminal_reply_bytes_generated = self
            .cumulative
            .terminal_reply_bytes_generated
            .saturating_add(reply.len() as u64);
        self.pending_reply_range = Some(start..start + reply.len());
        self.update_maxes();
        Ok(())
    }
}

impl Drop for Session {
    fn drop(&mut self) {
        // Best-effort cleanup: force-kill and reap the remaining child. This
        // may block, and failures cannot be reported from `Drop`.
        if self.exit_status.is_some() {
            match self.pty.take() {
                Some(Pty::Live(pty)) => {
                    let _ = pty.into_closing();
                }
                Some(Pty::Closing(_)) | None => {}
            }
            return;
        }
        let mut closing = match self.pty.take() {
            Some(Pty::Live(pty)) => pty.into_closing(),
            Some(Pty::Closing(closing)) => closing,
            None => return,
        };
        let _ = closing.signal_kill();
        let _ = closing.wait_and_reap();
    }
}

/// Per-pump byte and syscall budget accounting.
struct Budget {
    bytes: usize,
    syscalls: usize,
}

impl Budget {
    fn new(bytes: usize, syscalls: usize) -> Self {
        Self { bytes, syscalls }
    }

    fn consume(&mut self, bytes: usize, syscalls: usize) {
        self.bytes = self.bytes.saturating_sub(bytes);
        self.syscalls = self.syscalls.saturating_sub(syscalls);
    }

    fn bytes_left(&self) -> usize {
        self.bytes
    }

    fn exhausted(&self) -> bool {
        self.bytes == 0 || self.syscalls == 0
    }
}

/// Length of the intersection between unsent outbound bytes and a reply range.
fn pending_reply_unsent_len(write_offset: usize, range: Option<&Range<usize>>) -> usize {
    match range {
        Some(range) => range.end.saturating_sub(write_offset.max(range.start)),
        None => 0,
    }
}

#[cfg(test)]
mod tests {
    use super::pending_reply_unsent_len;
    use std::ops::Range;

    #[test]
    fn pending_reply_counts_only_intersection_with_unsent() {
        let range: Range<usize> = 100..105;
        assert_eq!(pending_reply_unsent_len(0, Some(&range)), 5);
        assert_eq!(pending_reply_unsent_len(100, Some(&range)), 5);
        assert_eq!(pending_reply_unsent_len(102, Some(&range)), 3);
        assert_eq!(pending_reply_unsent_len(105, Some(&range)), 0);
        assert_eq!(pending_reply_unsent_len(0, None), 0);
    }
}
